# Generated by Django 6.0.3 on 2026-04-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelTable(
            name='produto',
            table='produtos',
        ),
    ]
