# Generated by Django 6.0.5 on 2026-06-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_options_alter_produto_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('aneis', 'Anéis'), ('colares', 'Colares'), ('pulseiras', 'Pulseiras'), ('brincos', 'Brincos')], max_length=20),
        ),
    ]
