# Generated by Django 6.0.5 on 2026-06-25 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_categoria_produto_imagem_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categorias',
        ),
    ]
